apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uim-dataflow-service
spec:
  rules:
  - host: uim-dataflow.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uim-dataflow-service
            port:
              number: 80
