apiVersion: v1
kind: Service
metadata:
  name: uim-dataflow-service
  labels:
    app: uim-dataflow-service
spec:
  type: ClusterIP
  selector:
    app: uim-dataflow-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
